package com.destiny.angelsquaddatabase.Model.TipsAndTrick;

import com.destiny.angelsquaddatabase.Model.Model;

import java.util.ArrayList;

public class AngelDataTipsArgentWing {
    public static String[][] data = new String[][]{
            {"1",
                    "TAC-50",
                    "https://angelsquad.lytogame.com/karakter/assets/images/detail/argent/nicole.png",
                    "Anggota Argent Wings, berkepala dingin dan mata yang tajam, yang terbaik di kalangan Sniper. Di sisi lain, dia juga ahli dalam bidang intelijen dan strategi perang, dia merupakan seorang gadis yang bisa segala hal.\n" +
                            "\n" +
                            "Past Roles : Edward Elric - Full Metal Alchemist, Temari - Naruto, Pakunoda - Hunter x Hunter",
                    "Romi Park",
                    "Argent Wing",
                    "Nicole",
                    "Sniper",
                    "R",
                    "-",
                    "-",
                    "-",
                    "-",
                    "-",
                    "-",
            },
            {"2",
                    "M16A4",
                    "https://angelsquad.lytogame.com/karakter/assets/images/detail/argent/savannah.png",
                    "Pemimpin dari Argent Wings, sosok kakak perempuan yang kuat dan dapat diandalkan. Dia memimpin dalam pertempuran dan memerintah dengan berani dan pasti. Meskipun anggota tim menjauh darinya, mereka juga sangat mempercayainya. Dia adalah pemimpin alami.",
                    "Jun Shimizu",
                    "Argent Wing",
                    "Savannah",
                    "Assault Rifle",
                    "SR",
                    "-",
                    "-",
                    "-",
                    "-",
                    "-",
                    "-",
            },
            {"3",
                    "Aug",
                    "https://angelsquad.lytogame.com/karakter/assets/images/detail/argent/karen.png",
                    "Anggota Argent Wings dan Kapten dari Idol Group [V-girls] Gadis yang enerjik dan ceria tanpa dibuat-buat. Kemampuannya biasa saja, namun pesonanya yang unik selalu berhasil mendongkrak semangat teman-temannya, hal ini yang membuatnya tidak tergantikan.",
                    "Haruka Takahashi",
                    "Argent Wing",
                    "Karen",
                    "Assault Rifle",
                    "SSR",
                    "damage besar, fire rate tinggi, saat menggunakan skill aktif akurasi meningkat secara drastis, HP consume yang menyerang HP secara langsung ",
                    "pertahanan tergolong lemah, skill dapat dibatalkan dengan stun",
                    "aug adalah salah satu angel yang sering dijumpai di line up top arena. Damage yang besar, akurasi yang tinggi, serta fire rate yang gila membuat angel ini dijuluki preman arena. Dengan bermodalkan skill aktif level max dapat mengantarkan penggunanya menuju 100 besar top arena. Pengguna aug diwajibkan memiliki tank yang tebal dan keras agar aug tidak terserang oleh musuh. Kebanyakan pengguna aug akan kalah setelah barisan tank mereka ditembus.",
                    "di stage, skill aktif aug sulit diarahkan secara manual, etapi terdapat bug yang dapat membantu player mengarahkan dengan lebih tepat. Caranya adalah dengan memasuki mode scope, menghabiskan peluru, lalu disaat reload hampir selesai segera tekan skill aktif aug. player akan memasuki mode scope dan mendapat buff dari skill aktif aug",
                    "- Mag7 : mag7 memiliki damage resist yang baik saat mengeluarkan skill aktifnya, memitigasi sebagian damage aug. jika beruntung, pasif 1 dari mag7 akan memberikan buff kebal pada mag7 selama 2 detik yang secara efektif menghilangkan damage dari aug\n" +
                            "- MAC-10 : si kecil ini  memiliki damage resist hingga 56% yang berarti menghilangkan setengah dari damage yang diberikan musuh.\n" +
                            "- Remington 870 : walaupun kurang populer diantara player karena damage yang sangat random, skill aktif remington dapat membatalkan skill skill aktif musuh, mematikan pergerakan aug. \n" +
                            "- M16A4 : stun dapat menghentikan aug \n" +
                            "- QBZ-95 : stun dapat menghentikan aug\n" +
                            "- Angel dengan skill damage redution seperti famas, CZ75, dll. dapat mengurangi keefektifan aug\n",
                    "halibel",
            },
            {"4",
                    "Barreta1951",
                    "https://angelsquad.lytogame.com/karakter/assets/images/detail/argent/amy.png",
                    "Anggota terakhir [V-girls] yang memiliki sinar paling redup dalam grup. Walaupun dia menjadi seorang Idol, tidak bisa dipungkiri kalau kepopulerannya berada di tingkatan terbawah, hal ini membuat Amy menjadi kurang percaya diri dan dipenuhi pikiran negatif.",
                    "Aya Yokota",
                    "Argent Wing",
                    "Amy",
                    "Pistol",
                    "N",
                    "-",
                    "-",
                    "-",
                    "-",
                    "-",
                    "-",
            },
            {"5",
                    "F2000",
                    "https://angelsquad.lytogame.com/karakter/assets/images/detail/argent/julie.png",
                    "Sebagai peserta pelatihan yang baru bergabung, dia tergolong bertalenta. Setelah bergabung ke Argent Wings, dia diangkat menjadi Kapten untuk peserta pelatihan. Karena kemampuannya untuk mengukur kemampuan diri sangat baik, dia dicap sebagai masa depan Argent Wings, namun tidak membuatnya serta-merta menjadi Arogan, kebalikannya, dia merupakan orang yang sangat menghargai proses dan berkembang bersama teman-temannya.",
                    "Narumi Shinohara",
                    "Argent Wing",
                    "Julie",
                    "Assault Rifle",
                    "R",
                    "-",
                    "-",
                    "-",
                    "-",
                    "-",
                    "-",
            },
            {"6",
                    "FiveSeven",
                    "https://angelsquad.lytogame.com/karakter/assets/images/detail/argent/myako.png",
                    "Anggota Tim Tempur, sama seperti SKS, NyanNyan merupakan Angel dengan kualifikasi yang cukup rendah namun dengan kemampuan yang luar biasa. \"Karena pengaruh Factor Fusion, kepribadianku bercampur dengan hewan liar, namun kurasa tidak apa-apa.\"",
                    "Asuka Ito",
                    "Argent Wing",
                    "Myako",
                    "Pistol",
                    "SSR",
                    "-",
                    "-",
                    "-",
                    "-",
                    "-",
                    "-",
            },
            {"7",
                    "FN CAL",
                    "https://angelsquad.lytogame.com/karakter/assets/images/detail/argent/nina.png",
                    "Kapten Ghost Squad, namun karena sifatnya yang canggung dan ceroboh, dia menjadi kurang bisa diandalkan, bahkan bawahannya tidak pernah menjalankan perintahnya. Karena dia selalu bersikap serius, dia menjadi sangat kesulitan dalam bergaul dengan orang lain, hal ini sangat mengganggunya.\"",
                    "Narumi Shinohara",
                    "Argent Wing",
                    "Nina",
                    "Assault Rifle",
                    "SR",
                    "-",
                    "-",
                    "-",
                    "-",
                    "-",
                    "-",
            },
            {"8",
                    "G36",
                    "https://angelsquad.lytogame.com/karakter/assets/images/detail/argent/mia.png",
                    "Anggota [V-girls] ke-2. Selalu berpasangan dengan Aug dan mendukungnya selama pertempuran. Sama seperti Aug, Mia juga bercita-cita menjadi Idol semenjak kecil, oleh karena itu ketika Aug menawarkan posisi tersebut dia dengan senang hati menerima tawarannya dan menjadi duo Idol Angel.\"\n" +
                            "\n" +
                            "Past Roles : Kanae - Kimetsu no Yaiba, Alice - Sword Art Online, Darkness - Konosuba",
                    "Ai Kayano",
                    "Argent Wing",
                    "Mia",
                    "Assault Rifle",
                    "N",
                    "-",
                    "-",
                    "-",
                    "-",
                    "-",
                    "-",
            },
            {"9",
                    "Galil Ace",
                    "https://angelsquad.lytogame.com/karakter/assets/images/detail/argent/galia.png",
                    "Semasa Pelatihan, Loly kecil merupakan anak yang pandai dan bersikap baik, sehingga dia sangat disukai oleh teman-temannya. Walaupun kemampuannya tidak terlalu bagus, namun dia mampu untuk tetap tenang dan tak kenal takut dalam segala kondisi, dia menjadi orang yang dapat dipercaya oleh rekan-rekan satu timnya, terutama MAC-10 yang sangat mengaguminya.\"",
                    "Hiromi Sakuma",
                    "Argent Wing",
                    "Galia",
                    "Assault Rifle",
                    "SSR",
                    "-",
                    "-",
                    "-",
                    "-",
                    "-",
                    "-",
            },
            {"10",
                    "Lee-Enfield",
                    "https://angelsquad.lytogame.com/karakter/assets/images/detail/argent/erii.png",
                    "Diciptakan di Flaming Vita sebagai Angel Tingkat 4 dan sekarang tergabung sebagi Tim Tempur Argent Wings. Dari segi kemampuannya, dapat dinilai sangat jauh di atas Angel Tingkat 4 lainnya, bahkan dalam beberapa kesempatan dia bisa disejajarkan dengan TAC-50. Hanya saja kepintarannya sangat jauh dibawah sehingga dia tidak bisa bertarung sendirian.",
                    "-",
                    "Argent Wing",
                    "Erii",
                    "Sniper",
                    "SSR",
                    "-",
                    "-",
                    "-",
                    "-",
                    "-",
                    "-",
            },
            {"11",
                    "MAC-10",
                    "https://angelsquad.lytogame.com/karakter/assets/images/detail/argent/charlie.png",
                    "Anggota Pelatihan, saat ini dikatakan yang paling lemah diantara seluruh Angel di Argent Wings. Saat ini aku berusaha keras untuk memperbaiki kekuranganku dan mendapatkan Transformasi Angel yang sempurna di suatu saat.",
                    "Marina Hirabayashi",
                    "Argent Wing",
                    "Charlie",
                    "SMG",
                    "SR",
                    "-",
                    "-",
                    "-",
                    "-",
                    "-",
                    "-",
            },
            {"12",
                    "MP5",
                    "https://angelsquad.lytogame.com/karakter/assets/images/detail/argent/annie.png",
                    "Salah Satu Pilar Argent Wings, bergabung ke Federasi dan menjadi Angel atas kemauannya sendiri. Hobi sekali makan, terutama yang berbahan dasar daging, dia bisa makan banyak dan biasanya kalori yang diserap akan dibakar kembali melalui latihan intens, menjadikan fisiknya sempurna.",
                    "Koharu Nogata",
                    "Argent Wing",
                    "Annie",
                    "SMG",
                    "R",
                    "-",
                    "-",
                    "-",
                    "-",
                    "-",
                    "-",
            },
            {"13",
                    "Origin 12",
                    "https://angelsquad.lytogame.com/karakter/assets/images/detail/argent/ballari.png",
                    "Selain bahwa dia adalah Angel Tingkat 2 yang diciptakan di Federasi Bumi Manusia, segala informasi mengenai Ballari terkesan sangat misterius. Prajurit yang sangat berpengalaman dan dapat diandalkan dengan keseriusan dan berpendirian kuat. Ketika sedang santai sangat suka membaca di tempat yang tenang.",
                    "-",
                    "Argent Wing",
                    "Ballari",
                    "Shotgun",
                    "SSR",
                    "-",
                    "-",
                    "-",
                    "-",
                    "-",
                    "-",
            },
            {"14",
                    "P90",
                    "https://static.wikia.nocookie.net/angelsquad/images/c/c2/P90.png/revision/latest/scale-to-width-down/1000?cb=20210822114437&path-prefix=id",
                    "Anggota Tim Tempur, kemampuannya sekelas dengan SKS, mereka berdua sama-sama memiliki kemampuan Limit Break yang kuat dan mampu membawa tim untuk memenangkan pertempuran. Namun, dia sangat sulit untuk disadarkan karena dia cenderung mudah mengantuk.",
                    "Yukiko Ayamiya",
                    "Argent Wing",
                    "Vivienne",
                    "SMG",
                    "SSR",
                    "-",
                    "-",
                    "-",
                    "-",
                    "-",
                    "-",
            },
            {"14",
                    "PP-Bison",
                    "https://angelsquad.lytogame.com/karakter/assets/images/detail/argent/irina.png",
                    "Selain fakta bahwa dia merupakan Angel Tingkat 2 dari Federasi Bumi Manusia, tidak ada lagi yang bisa diketahui tentangnya. Karena efek samping dari Factor Fusion, terdapat kelainan yang unik pada dirinya, yang membuat dia memiliki hubungan khusus dengan Komandan.\n",
                    "Yuriko Yano",
                    "Argent Wing",
                    "Irina",
                    "SMG",
                    "SSR",
                    "Shield yang tebal sangat berguna dalam menyelesaikan stage.",
                    "hanya mengandalkan shield sehingga kurang cocok untuk digunakan dalam arena",
                    "pp-bison merupakan angel SSR yang akan didapatkan oleh player. SMG ini sangat berguna dalam menyelesaikan stage sehingga disarankan untuk tidak melebur angel ini. Skill pasif pertamanya yang meregenerasi shield sangat berguna untuk tahan badan di stage. Skill asif terakhirnya memberi bonus damage yang besar sehingga PP bison juga mampu membantu memberikan damage di stage.",
                    "sebagai tank, PP-bison dapat melakukan tugasnya walau hanya memiliki 1 skill pasif, jika ingin berhemat sumberdaya, disarankan untuk tidak melakukan limit break lebih dari sekali. ",
                    "-",
                    "halibel",
            },
            {"15",
                    "QSZ92",
                    "https://angelsquad.lytogame.com/karakter/assets/images/detail/argent/shimotsuki.png",
                    "Terlahir di Flaming Vita, parameter kekuatannya dalam bertarung sebagai Angel sangat tinggi untuk Angel Tingkat 4, yang membuatnya menjadi kebanggan organisasi. Sangat sulit bergaul karena kepribadiannya.",
                    "Seki Yurie",
                    "Argent Wing",
                    "Shimotsuki ",
                    "Pistol",
                    "SR",
                    "-",
                    "-",
                    "-",
                    "-",
                    "-",
                    "-",
            },
            {"16",
                    "SKS",
                    "https://angelsquad.lytogame.com/karakter/assets/images/detail/argent/taniro.png",
                    "Sebagai anggota dari Tim Tempur, dia diangkat menjadi Kapten karena pencapaiannya yang sangat luar biasa. Salah satu yang terbaik dari Angel Tingkat 4, bahkan bisa dibandingkan dengan senior-seniornya.",
                    "Yukio Yoshida",
                    "Argent Wing",
                    "Taniro",
                    "Sniper",
                    "SSR",
                    "-",
                    "-",
                    "-",
                    "-",
                    "-",
                    "-",
            },
            {"17",
                    "SVD",
                    "https://angelsquad.lytogame.com/karakter/assets/images/detail/argent/akira.png",
                    "Anggota Ghost Squad, wanita menakutkan yang menyatakan dirinya sebagai Ratu Teror. Dalam hal kemampuan, dia berada jauh diatas rata-rata. Sebagai Sniper, kemampuannya tidak bisa dikesampingkan jika dibandingkan rekan-rekan yang satu tingkat dengannya.",
                    "Nozomi Yamane",
                    "Argent Wing",
                    "Akira",
                    "Sniper",
                    "R",
                    "-",
                    "-",
                    "-",
                    "-",
                    "-",
                    "-",
            },
            {"18",
                    "TEC-DC9",
                    "https://angelsquad.lytogame.com/karakter/assets/images/detail/argent/jenny.png",
                    "Anggota Ghost Squad, melakukan segala sesuatunya sesuai caranya, tanpa koordinasi dan dengan cara yang ekstrem. Sebelum menjadi Angel, dia adalah anggota Mafia, namun karena tidak bisa bertahan dari serangan Alien, dia secara sukarela bergabung sebagai Angel.",
                    "Takao Koizumi",
                    "Argent Wing",
                    "Jenny",
                    "SMG",
                    "N",
                    "-",
                    "-",
                    "-",
                    "-",
                    "-",
                    "-",
            },
            {"19",
                    "Thompson",
                    "https://angelsquad.lytogame.com/karakter/assets/images/detail/argent/mirai.png",
                    "Lahir di Federasi Bumi Manusia, selama tergabung di Pasukan Khusus, dia memiliki kedekatan khusus dengan Komandan dan M16A4. Setelah Argent Wings didirikan, dia tetap mengikuti langkah Komandan. Berbeda dengan M16A4 dan yang lain, dia tidak mendapatkan tugas yang berhubungan langsung dengan musuh, melainkan tugas khusus yang diberikan oleh Komandan.",
                    "Nao Ueda",
                    "Argent Wing",
                    "Mirai",
                    "SMG",
                    "R",
                    "-",
                    "-",
                    "-",
                    "-",
                    "-",
                    "-",
            },
            {"19",
                    "Type 79",
                    "https://angelsquad.lytogame.com/karakter/assets/images/detail/argent/lily.png",
                    "Anggota [V-girls], gadis penuh semangat yang sangat suka Fashion Oriental. Cheongsam yang dipakai merupakan pertanda preferensi dan ketekunan. Karena itulah dia bisa diterima dan diakui oleh semua orang sebagai anggota grup Idol.",
                    "Saya Horigome",
                    "Argent Wing",
                    "Lily",
                    "SMG",
                    "R",
                    "-",
                    "-",
                    "-",
                    "-",
                    "-",
                    "-",
            },
            {"20",
                    "Vector",
                    "https://angelsquad.lytogame.com/karakter/assets/images/detail/argent/alyssa.png",
                    "Anggota Tim Tempur, cukup kuat untuk membuat dirinya sendiri menjadi lebih menonjol dibanding SKS. Namun karena dia mengidap \"Chuunibyo\", dia menjadi sulit dalam bicara dan membuatnya menjadi sulit dimengerti. Bahkan sudah sampai di tahap \"Aneh\" dikalangan F.L.D.\n" +
                            "\n" +
                            "Past Roles : Toru Hagakure - Boku no Hero Academia",
                    "Kaori Nazuka",
                    "Argent Wing",
                    "Alyssa",
                    "SMG",
                    "SR",
                    "-",
                    "-",
                    "-",
                    "-",
                    "-",
                    "-",
            },
            {"21",
                    "VSS",
                    "https://angelsquad.lytogame.com/karakter/assets/images/detail/argent/anna.png",
                    "Anggota Tim Pelatihan, kemampuannya sangat terbatas namun bukan berarti hanya biasa aja. Untuk kemampuan Operasional nya sendiri dia bahkan lebih baik F2000. Menyukai makanan manis, dan sangat suka membawa makanan manis ke kamarnya. Terkadang bersifat kekanakan.",
                    "Eri Kuramoto",
                    "Argent Wing",
                    "Anna",
                    "Sniper",
                    "R",
                    "-",
                    "-",
                    "-",
                    "-",
                    "-",
                    "-",
            },
            {"22",
                    "CZ75",
                    "https://angelsquad.lytogame.com/karakter/assets/images/detail/argent/kasuga.png",
                    "Anggota Argent Wings yang bertugas untuk mengirimkan dukungan komunikasi terhadap seluruh tim. Sebagai Angel, kemampuan fisik dan otaknya jauh diatas rata-rata, namun karena kepribadiannya, dia tidak diizinkan untuk terjun langsung ke medan tempur.",
                    "Kaori Yoshioka",
                    "Argent Wing",
                    "Kasuga",
                    "Pistol",
                    "SR",
                    "-",
                    "-",
                    "CZ75 adalah suport yang wajib dimiliki oleh player karena dia merupakan angel dengan skill heal yang berguna sampai kapanpun. Angel ini adalah drop di stage 3-5. Angel ini juga dapat diturunkan di arena karena skill aktifnya menambah damage dan damage resist dari teman satu tim.",
                    "bukalah skill pasif pertama dari CZ75 dengan menggunakan limit break, lalu upgrade skill tersebut dan taruh CZ75 di suport.",
                    "-",
                    "halibel",
            },
    };
    public static ArrayList<Model> getListData(){
        Model model = null;
        ArrayList<Model> list = new ArrayList<>();
        for (String[] aData : data) {
            model = new Model();
            model.setId(aData[0]);
            model.setNama(aData[1]);
            model.setGambar(aData[2]);
            model.setDeskripsi(aData[3]);
            model.setVa(aData[4]);
            model.setFaction(aData[5]);
            model.setRealname(aData[6]);
            model.setWeapon(aData[7]);
            model.setRarity(aData[8]);
            model.setKelebihan(aData[9]);
            model.setKekurangan(aData[10]);
            model.setIntroduksi(aData[11]);
            model.setTips(aData[12]);
            model.setCounter(aData[13]);
            model.setAuthor(aData[14]);
            list.add(model);
        }

        return list;
    }
}
